package Model.Generate;

public class CheckboxesDataName {
    String[] pork = {
            "Baboy (Pork)",
            "Giniling na Baboy (Ground Pork)",
            "Kasim (Pork Shoulder)",
            "Liempo (Pork Belly)",
            "Tadyang (Pork Ribs)",
            "Lomo (Pork Tenderlion)",
            "Pata (Pork Hock)",
            "Tenga ng Baboy (Pig Ears)",
            "Atay ng Baboy (Pork Liver)",
            "Baga ng Baboy (Pork Lungs)",
            "Bato ng Baboy (Pork Kidney)",
            "Isaw ng Baboy (Pig's Intestine) ",
            "Dugo ng Baboy (Pork Blood)",
            "Puso ng Baboy (Pig Heart)",
            "Pork Chop",
            "Pork Chicharon",
            "Bagnet",
            "Lechon kawali",
            "Liver Spread",
            "Pig Stomach",
            "Pork Ham",
            "Chorizo de Bilbao",
            "Patties",
            "Ox Tripe",
            "Hotdog",
            "Sausage",
            "Bacon",
            "Ribs (Baby Back ribs)",
            "Longanisa",
            "Ulo ng Baboy (Pork Head)"
    };
    String[] chicken = {
            "Manok (Chicken)",
            "Buong Manok (Whole Chicken)",
            "Atay ng Manok (Chicken Liver)",
            "Pecho ng Manok (Chicken Breast)",
            "Hita ng Manok (Thigh)",
            "Puso ng Manok (Chicken Heart)",
            "Giniling na Manok (Ground Chicken)",
            "Paa ng manok (Chicken feet)",
            "Balat ng Manok (Chicken Skin)",
            "Balunbalunan (Gizzard)",
            "Pakpak (Chicken Wings)",
            "Ulo ng manok (Chicken heads)",
            "Chicken Intestines (Proben)",
            "Chicken drumstick",
            "Leeg ng Manok (Chicken Neck)",
            "Lomo (Chicken tenderloin)",
            "Chicken blood"
    };
    String[] beef = {
            "Baka (Beef)",
            "Beef brisket",
            "Beef sirloin",
            "Tadyang (Beef ribs)",
            "Beef oxtail",
            "Giniling na baka (Ground beef)",
            "Buto-buto (Beef shanks)",
            "Dila ng baka (Beef lengua)",
            "Litson Baka",
            "Corned beef",
            "Beef Tenderloin",
            "Beef chuck",
            "Beef Trotters",
            "Tuwalya (Beef tripe)",
            "Bituka ng baka (Beef intestine)",
            "Puso ng baka (Beef heart)",
            "Atay ng baka (Beef liver)",
            "Bato ng baka (Beef kidney)",
            "Carabeef Ground",
            "Kasukasuan ng Baka (Beef Short Ribs)"
    };
    String[] fish = {
            "Isda (Fish)",
            "Bangus (Milkfish)",
            "Tilapia",
            "Galunggong (Round Scad)",
            "Tulingan (Mackerel Tuna)",
            "Lapu-Lapu (Grouper)",
            "Dilis (Dried fish)",
            "Tuyo (Dried Fish)",
            "Tambakol (Yellowfin Tuna)",
            "Hito (Catfish)",
            "Dalagang Bukid (Yellowtail Fusilier)",
            "Daing (Fried dried fish)",
            "Sardines",
            "Salmon",
            "Sapsap (Butterfish)",
            "Isdang pilak (Silver fish)",
            "Alumahan (Long-jawed Mackerel)",
            "Tinapa (Herring like fish)",
            "Maya maya (Red snapper)",
            "Danggit (Spinefoot fish)",
            "Canned Tuna",
            "Pipikay (Mahi-mahi)",
            "Babangkatan (Pompano)",
            "Jeprox (Smelt)",
            "Swait Fish",
            "Hipon (Shrimp)",
            "Sugpo (Prawn)",
            "Alimango (Mud crab)",
            "Alimasag (Blue crabs)",
            "Talangka (River crab)",
            "Pusit (Squid)",
            "Tahong (Mussle)",
            "Talaba (Oyster)",
            "Kuhol (Golden apple snails)",
            "Dried shrimp",
            "Squid Balls",
            "Dagat kabibi (Sea scallops)",
            "Dilis (Dried fish)",
            "Tanigue",
            "Mahi mahi (Dolphinfish)",
            "Halibut (Right-eye flounder)",
            "Dulong (Whitebait Fish)"
    };



    String[] vegetables = {
            "Sitaw (String beans)",
            "Kalabasa (Squash)",
            "Okra (Lady's finger)",
            "Talong (Eggplant)",
            "Ampalaya (Bitter gourd)",
            "Kamote (Sweet potato)",
            "Kamatis (Tomato)",
            "Malunggay leaves (Moringa leaves)",
            "Dahon ng kalabasa (Squash flower)",
            "Green Papaya",
            "Gabi (Taro leaves)",
            "Patola (Sponge gourd)",
            "Baguio beans (Green beans)",
            "Tanglad (Lemongrass)",
            "Saluyot (Jute Leaves)",
            "Alugbati (Spinach)",
            "Kulitis (Amaranth leaves)",
            "Berdeng atsal (Green bell pepper)",
            "Pulang atsal (Red bell pepper)",
            "Kangkong",
            "Repolyo (Cabbage)",
            "Kamias (Tree sorrel)",
            "Munggo (Mung Beans)",
            "Singkamas",
            "Carrots",
            "Kinchay (Parsley)",
            "Sayote (Vegetable pear)",
            "Patatas (Potatoes)",
            "Litsugas (Lettuce)",
            "Ubod (Hearts of palm)",
            "Puso ng saging (Banana Blossom)",
            "Togue (Mung bean sprouts)",
            "Pako (Fiddlehead Fern)",
            "Cauliflower",
            "Kintsay (Cilantro)",
            "Pechay (Snow cabbage)",
            "Upo (Bottle gourd)",
            "Labanos (White radish)",
            "Tawsi (Black beans)",
            "Kadyos (Pigeon pea)",
            "Shallots",
            "Celery",
            "Pipino (Cucumber)",
            "Chives",
            "Basil leaves",
            "Dahon ng Sili (Hot Pepper Leaves)",
            "Tamarind leaves",
            "Green peas",
            "Mushrooms",
            "Pickle",
            "Sitsaro (Snow Peas)",
            "Chickpeas (garbanzo beans)",
            "Bamboo Shoots",
            "Atchara",
            "Mustasa (Mustard leaves)",
            "Kamote leaves (Sweet potato leaves)",
            "Labong (Bamboo Shoots)",
            "Broccoli",
            "Ampalaya leaves",
            "Sigarilyas (Winged beans)",
            "Asparagus",
            "Zucchini",
            "Wansoy (Dill)",
            "Kale leaves",
            "Dahon ng paminta (Hot pepper leaves)",
            "Shaoxing Wine",
            "Braising liquid",
            "Broccoli Florets",
            "Kimchi",
            "baby bok choy"
    };


    String[] condiments = {
            "Bawang (Garlic)",
            "Garlic Paste",
            "Garlic powder",
            "Sibuyas (Onion)",
            "Onion powder",
            "Onion leeks",
            "Scallions",
            "Luya (Ginger)",
            "Ginger powder",
            "Luyang Dilaw (Turmeric)",
            "Asukal (Sugar)",
            "Paminta (Ground black pepper)",
            "Ground ginger",
            "Ground tumeric",
            "Asin (Salt)",
            "himalayan salt",
            "Msg",
            "Magic sarap",
            "Ginisa mix",
            "Sinigang Sampalok Mix",
            "Sinigang Sampalok With Gabi Mix",
            "Seasoning Mix",
            "Kare Kare Recipe Mix",
            "Crab and corn mix",
            "Crispy Mix",
            "Flavor Seasoning Mix",
            "Chicken powder",
            "Curry Powder",
            "Turmeric Powder",
            "Pork Seasoning",
            "Ginataang Gulay Mix",
            "Chilli flakes",
            "Atsuete (Annatto seeds)",
            "Coriander Seeds",
            "Sesame seeds",
            "Paprika",
            "Star Anise",
            "Cinnamon",
            "Nutmeg",
            "Cumin",
            "thyme",
            "Tarragon",
            "Cardamom",
            "Dried Parsley",
            "Sibot",
            "Pandan (Screwpine Leaves)",
            "Tanglad (Lemongrass)",
            "Sampalok (Tamarind)",
            "Kinchay (Parsley)",
            "Dahon ng Saging (Banana Leaves)",
            "Dahon ng Laurel (Bay Leaves)",
            "Curry leaves",
            "Coriander leaves",
            "Miso paste",
            "Cayenne pepper",
            "Dried basil",
            "Soy paste",
            "Garam Masala",
            "Alfredo sauce",
            "Dried chili flakes",
            "Saffron",
            "Chili Powder",
            "Rosemary",
            "Chicken and corn mix",
            "Oregano leaves",
            "Cream Mushroom Soup",
            "Annatto oil",
            "Annatto powder",
            "Beef bile",
            "Ground cloves",
            "Knorr Cream of Pumpkin",
            "Mustard powder",
            "Saffron",
            "Cinnamon Stick",
            "Peppercorn",
            "Atsuete Oil",
            "Shrimp Broth",
            "Five Spice Powder",
            "Habanero Pepper Sauce",
            "Sheets Norii Wrapper",
            "kasubha",
            "Coconut Curry Paste"

    };
    String[] sauces = {
            "Toyo (Soy sauce)",
            "Suka (Vinegar)",
            "Liquid Seasoning",
            "Ketchup",
            "Tomato sauce",
            "Tomato Paste",
            "Tomato ketchup",
            "Chili sauce",
            "Sweet chili sauce",
            "Hoisin sauce",
            "Worcestershire Sauce",
            "Hot Sauce",
            "Sriracha",
            "Mang Tomas",
            "Bagoong alamang (Shrimp paste)",
            "Barbecue Sauce",
            "Oyster sauce",
            "Bagoong isda (Anchovy sauce)",
            "Patis (Fish sauce)",
            "Buro Sauce",
            "Shrimp Cubes",
            "Pork Cubes",
            "Beef Cubes",
            "Chicken Cubes",
            "Chicken Broth",
            "Beef Broth",
            "Pork Broth",
            "Hugas bigas (Rice washing)",
            "Calamansi juice",
            "Pineapple juice",
            "Lemon juice",
            "Apple Juice",
            "Sprite",
            "Soft Drink",
            "Soda",
            "Lemon lime soda",
            "Water",
            "Wine",
            "Fish cubes",
            "Vegetable broth",
            "Apple Cider Vinegar",
            "Spaghetti Sauce",
            "Coca-cola (Coke)",
            "Baking soda",
            "Banana Ketsup",
            "Lechon Sauce",
            "Teriyaki sauce",
            "Beer",
            "Balsamic vinaigrette",
            "Lemon Lime Soda",
            "Batwan Fruit",
            "Coconut toddy"
    };
    String[] fruits = {
            "Langka (Jackfruit)",
            "Siling labuyo (Red Chili)",
            "Siling haba (Green Chili)",
            "Mais (Sweet corn)",
            "Saging saba (Sweet plantain)",
            "Peanut",
            "Lemon",
            "Pineapple",
            "Coconut",
            "green olives",
            "black olives",
            "Calamansi",
            "Pineapple",
            "Raisins",
            "Orange",
            "Banana",
            "Green mango",
            "Tamarind",
            "Guava",
            "Santol",
            "Almonds",
            "Baby corn",
            "Katmon Fruits",
            "Coconut"
    };

    String[] pantry = new String[]{
            "Cooking oil",
            "Butter",
            "Margarine",
            "Mantikilya (Butter)",
            "Itlog (Egg)",
            "Quail Eggs (Pugo)",
            "Itlog-maalat (Salted Egg)",
            "Harina (Flour)",
            "All purpose flour",
            "Rice flour",
            "Cornstarch",
            "Yeast",
            "Baking Powder",
            "All Purpose Cream",
            "Whipping Cream",
            "Gatas (Milk)",
            "Evaporated Milk",
            "Coconut Milk (Diluted)",
            "Gata ng niyog (Coconut milk)",
            "Krema ng niyog (Coconut cream)",
            "Vanilla extract",
            "Keso (Cheese)",
            "Mayonnaise",
            "Tokwa (Tofu)",
            "Kanin (Rice)",
            "Kaning malagkit (Glutinous rice)",
            "Lumpia Wrapper",
            "Bihon noodles",
            "Egg Noodles",
            "Spaghetti noodles",
            "Sotanghon Noodles",
            "Misua",
            "Mustard",
            "Shortening",
            "Peanut Butter",
            "Honey",
            "Honey mustard",
            "Slurry",
            "Spring roll wrappers",
            "Gyoza Wrapper",
            "Breadcrumbs",
            "Food Coloring",
            "Wonton Wrapper",
            "Macaroni",
            "Odong noodles",
            "Heavy cream",
            "Tortillas",
            "Taco shells",
            "Sesame Oil",
            "Molo wrappers",
            "Maple Syrup",
            "Lasagna Sheets",
            "Olive Oil",
            "Siomai wrappers",
            "Sour cream",
            "Pasta",
            "Condensed milk",
            "Yogurt",
            "Fettuccine pasta",
            "Crackers\n",
            "Tinapay (Bread)\n",
            "Cream\n",
            "Ssamjang (Soy Bean Paste)\n",
            "Tinapa Flakes\n",
            " Water Chestnuts\n",
            "Shao Xing Wine\n",
            "Tapioca Starch\n",
            "Wheat Noodles\n",
            "Fresh Miki",
            "Flat Noodles",
            "Rice Wine",
            "Malagkit Rice",
            "Loaf Bread",
            "Vienna Sausage",
            "Sweet Pickle Relish",
            "Cheddar Cheese",
            "Dried Rosemary Leaves"

    };
    //getters
    public String[] getPorkIngredientsList(){return  pork;}
    public String[] getChickenIngredientsList(){
        return chicken;
    }
    public String[] getBeefIngredientsList(){
        return beef;
    }
    public String[] getFishIngredientsList(){
        return fish;
    }
    public String[] getVegetableIngredientList(){
        return vegetables;
    }
    public String[] getCondimentsIngredientsList(){
        return condiments;
    }
    public String[] getSaucesIngredientsList(){return sauces;}
    public String[] getFruitsIngredientsList(){return fruits;}
    public String[] getPantryIngredientsList(){return pantry;}
}
